language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
  - openjdk7

os:
  - linux
  - osx


before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew tap caskroom/cask; brew install Caskroom/cask/java; fi
